#!/usr/bin/env bash

# Set script scope environment variables for dev or CI.
export APP_PORT=${APP_PORT:-80}
export DB_PORT=${DB_PORT:-3306}
export DB_ROOT_PASS=${DB_ROOT_PASS:-secret}
export DB_NAME=${DB_NAME:-book_a_test}
export DB_USER=${DB_USER:-book_a_test}
export DB_PASS=${DB_PASS:-secret}
export CFN_TEMPLATE=${CFN_TEMPLATE:-cloudformation}

# Decide which docker-compose file to use.
COMPOSE_FILE="dev"

# Disable pseudo-TTY allocation for CI (Travis).
# The -T flag removes interaction.
TTY=""

# Travis CI provides a CI flag which can be used to check
# if this is running in a CI environment.
if [ ${CI:-false} == "true" ]; then
    COMPOSE_FILE="ci"
    TTY="-T"
fi

COMPOSE="docker-compose -f docker-compose.yml -f docker-compose.$COMPOSE_FILE.yml"

# Pass arguments to docker-compose, or default to docker-compose ps.
if [ $# -gt 0  ]; then
    case "$1" in

        art|artisan )
            shift 1
            ${COMPOSE} run --rm ${TTY} \
                api \
                php artisan "$@"
            ;;

        composer )
            shift 1
            ${COMPOSE} run --rm ${TTY} \
                api \
                composer "$@"
            ;;

        npm )
            shift 1
            ${COMPOSE} run --rm ${TTY} \
                node \
                npm "$@"
            ;;

        cfn )
            ${COMPOSE} run --rm troposphere > aws/${CFN_TEMPLATE}.json
            cat aws/${CFN_TEMPLATE}.json
            ;;

        * ) ${COMPOSE} "$@"; ;;

    esac
else
    ${COMPOSE} ps
fi
