#!/usr/bin/env bash

# Requires the following environment variables:
# $CIRCLE_WORKING_DIRECTORY = The directory of the project.
# $CIRCLE_SHA1 = The SHA1 hash of the last commit of the current build.
# $REPO_URI = The URI of the Docker repo to tag the image with.
# $ENV_SECRET_ID = The ID of the .env file in AWS Secrets Manager (defaults to ".env").
# $PUBLIC_KEY_SECRET_ID = The ID of the OAuth public key file in AWS Secrets Manager (default to "oauth-public.key").
# $PRIVATE_KEY_SECRET_ID = The ID of the OAuth private key file in AWS Secrets Manager (default to "oauth-private.key").

# Bail out on first error.
set -e

# Package the app.
echo "Packaging the app..."
cd ${CIRCLE_WORKING_DIRECTORY}
# "archive" gives us useful tools - we can use .gitattributes
# to `export-ignore` extraneous files.
git archive --format=tar --worktree-attributes ${CIRCLE_SHA1} | tar -xf -  -C ${CIRCLE_WORKING_DIRECTORY}/docker/api/packaged

# Production Build Steps.
echo "Installing composer dependencies..."
cd ${CIRCLE_WORKING_DIRECTORY}/docker/api/packaged
./develop composer install --no-dev --optimize-autoloader

echo "Installing NPM dependencies..."
./develop npm ci

echo "Compiling assets..."
./develop npm run prod
docker run --rm \
    -w /opt \
    -v $(pwd)/docker/api/packaged:/opt ubuntu:16.04 bash -c "rm -rf node_modules"

# Get the .env file.
echo "Downloading .env file..."
aws secretsmanager get-secret-value \
    --secret-id ${ENV_SECRET_ID} | \
    python -c "import json,sys;obj=json.load(sys.stdin);print obj['SecretString'];" > .env

# Get the OAuth keys.
echo "Downloading public OAuth key..."
aws secretsmanager get-secret-value \
    --secret-id ${PUBLIC_KEY_SECRET_ID} | \
    python -c "import json,sys;obj=json.load(sys.stdin);print obj['SecretString'];" > storage/oauth-public.key

echo "Downloading private OAuth key..."
aws secretsmanager get-secret-value \
    --secret-id ${PRIVATE_KEY_SECRET_ID} | \
    python -c "import json,sys;obj=json.load(sys.stdin);print obj['SecretString'];" > storage/oauth-private.key

# Build the Docker image with latest code.
echo "Building Docker images..."
cd ${CIRCLE_WORKING_DIRECTORY}/docker/api
docker build \
    -t ${REPO_URI}:latest \
    -t ${REPO_URI}:${CIRCLE_SHA1} .

# Clean up packaged directory, but only if not in CI environment.
echo "Cleaning up..."
cd ${CIRCLE_WORKING_DIRECTORY}/docker/api/packaged
PWD=$(pwd)
if [[ "$PWD" == "$CIRCLE_WORKING_DIRECTORY/docker/api/packaged" ]]; then
    # The "vendor" directory (any any built assets!) will be owned
    # as user "root" on the Linux file system
    # So we'll use Docker to delete them with a one-off container
    docker run --rm \
        -w /opt \
        -v $(pwd):/opt ubuntu:16.04 bash -c "rm -rf ./* && rm -rf ./.git* && rm .env*"
    touch .gitkeep
fi
