#!/usr/bin/env bash

usage() {
    echo "Usage: $0 [-s <string> The name of the ECS service] [-p <string> The name of the AWS profile]" 1>&2;
    exit 1;
}

while getopts ":s:p:" o; do
    case "${o}" in
        s)
            SERVICE=${OPTARG}
            ;;
        p)
            PROFILE=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done

# Exit if no service is passed.
if [ -z "$SERVICE" ]; then
    usage
fi

# Login to the ECR.
if [ -z "$PROFILE" ]; then
    $(aws ecr get-login --no-include-email)
else
    $(aws ecr get-login --no-include-email --profile=${PROFILE})
fi

# Push the Docker image to ECR.
docker push ${REPO_URI}:latest
# docker push ${REPO_URI}:${TRAVIS_COMMIT}

# Update the service.
aws ecs update-service --service $SERVICE --force-new-deployment